Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 209, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/sqlite3/base.py", line 209, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
[28/Apr/2021 08:46:40] "GET / HTTP/1.1" 200 4067
[28/Apr/2021 08:46:46] "GET /admin HTTP/1.1" 301 0
[28/Apr/2021 08:46:46] "GET /admin/ HTTP/1.1" 302 0
[28/Apr/2021 08:46:46] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2214
[28/Apr/2021 08:46:46] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[28/Apr/2021 08:46:46] "GET /static/admin/css/login.css HTTP/1.1" 200 939
[28/Apr/2021 08:46:46] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[28/Apr/2021 08:46:46] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[28/Apr/2021 08:46:46] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[28/Apr/2021 08:46:46] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[28/Apr/2021 08:46:47] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[28/Apr/2021 08:46:47] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[28/Apr/2021 08:46:47] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[28/Apr/2021 08:46:47] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[28/Apr/2021 08:46:47] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[28/Apr/2021 08:46:47] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[28/Apr/2021 08:46:47] "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
[28/Apr/2021 08:46:47] "GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
[28/Apr/2021 08:46:47] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[28/Apr/2021 08:46:51] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2376
[28/Apr/2021 08:46:51] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[28/Apr/2021 08:46:53] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2376
[28/Apr/2021 08:47:03] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2375
[28/Apr/2021 08:47:03] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[28/Apr/2021 08:47:03] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[28/Apr/2021 08:47:13] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[28/Apr/2021 08:47:13] "GET /admin/ HTTP/1.1" 200 5540
[28/Apr/2021 08:47:13] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[28/Apr/2021 08:47:13] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[28/Apr/2021 08:47:13] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
Not Found: /img/icon-addlink.svg
Not Found: /img/icon-changelink.svg
[28/Apr/2021 08:47:13] "GET /img/icon-addlink.svg HTTP/1.1" 404 2495
[28/Apr/2021 08:47:13] "GET /img/icon-changelink.svg HTTP/1.1" 404 2504
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
[28/Apr/2021 08:51:19] "GET /admin/ HTTP/1.1" 200 5540
[28/Apr/2021 08:51:19] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[28/Apr/2021 08:51:19] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[28/Apr/2021 08:51:19] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[28/Apr/2021 08:51:19] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[28/Apr/2021 08:51:19] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[28/Apr/2021 08:51:19] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[28/Apr/2021 08:51:20] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /img/icon-changelink.svg
Not Found: /img/icon-addlink.svg
[28/Apr/2021 08:51:20] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[28/Apr/2021 08:51:20] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[28/Apr/2021 08:51:20] "GET /img/icon-changelink.svg HTTP/1.1" 404 2504
[28/Apr/2021 08:51:20] "GET /img/icon-addlink.svg HTTP/1.1" 404 2495
[28/Apr/2021 08:51:20] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[28/Apr/2021 08:51:20] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[28/Apr/2021 08:51:23] "GET / HTTP/1.1" 200 4067
[28/Apr/2021 08:51:25] "GET / HTTP/1.1" 200 4067
[28/Apr/2021 08:51:26] "GET /blogger/ HTTP/1.1" 200 3630
[28/Apr/2021 08:51:27] "GET /contact/index HTTP/1.1" 200 3243
[28/Apr/2021 08:51:37] "POST /contact/index HTTP/1.1" 200 3350
[28/Apr/2021 08:51:43] "POST /contact/index HTTP/1.1" 302 0
[28/Apr/2021 08:51:43] "GET /contact/successful HTTP/1.1" 200 2511
[28/Apr/2021 08:51:50] "GET / HTTP/1.1" 200 4067
[28/Apr/2021 08:51:54] "GET /contact/index HTTP/1.1" 200 3243
[28/Apr/2021 08:51:55] "GET /blogger/ HTTP/1.1" 200 3630
[28/Apr/2021 08:52:01] "GET / HTTP/1.1" 200 4067
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
Not Found: /home/index.html
[25/Jan/2022 22:33:45] "GET /home/index.html HTTP/1.1" 404 2541
Not Found: /favicon.ico
[25/Jan/2022 22:33:45] "GET /favicon.ico HTTP/1.1" 404 2468
[25/Jan/2022 22:34:14] "GET /home HTTP/1.1" 301 0
[25/Jan/2022 22:34:14] "GET /home/ HTTP/1.1" 200 4067
[25/Jan/2022 22:34:14] "GET /static/main/base.css HTTP/1.1" 200 514
[25/Jan/2022 22:34:14] "GET /static/home/home.css HTTP/1.1" 200 51
[25/Jan/2022 22:34:14] "GET /static/home/images/blog_home_pic1.jpeg HTTP/1.1" 200 292330
[25/Jan/2022 22:34:14] "GET /static/home/images/blog_home_pic3.jpeg HTTP/1.1" 200 169532
[25/Jan/2022 22:34:14] "GET /static/home/images/blog_home_pic2.jpeg HTTP/1.1" 200 375740
[25/Jan/2022 22:34:18] "GET /blogger/ HTTP/1.1" 200 3630
[25/Jan/2022 22:34:18] "GET /static/blogger/blogger.css HTTP/1.1" 200 165
[25/Jan/2022 22:34:19] "GET /contact/index HTTP/1.1" 200 3243
[25/Jan/2022 22:34:19] "GET /static/contact/contact.css HTTP/1.1" 200 371
[25/Jan/2022 22:34:21] "GET / HTTP/1.1" 200 4067
[25/Jan/2022 22:34:23] "GET /blogger/ HTTP/1.1" 200 3630
[25/Jan/2022 22:34:28] "GET / HTTP/1.1" 200 4067
[25/Jan/2022 22:34:31] "GET /contact/index HTTP/1.1" 200 3243
[25/Jan/2022 22:34:44] "POST /contact/index HTTP/1.1" 200 3349
[25/Jan/2022 22:34:51] "GET / HTTP/1.1" 200 4067
/opt/blogger_ui/src/app/main/settings.py changed, reloading.
Performing system checks...

January 25, 2022 - 22:33:36
Django version 3.2, using settings 'main.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
/opt/blogger_ui/src/app/main/settings.py changed, reloading.
Performing system checks...


You have 19 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, blogger, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
January 25, 2022 - 22:37:01
Django version 3.2, using settings 'main.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
[25/Jan/2022 22:38:40] "GET / HTTP/1.1" 200 4067
[25/Jan/2022 22:38:42] "GET /blogger/ HTTP/1.1" 200 3630
[25/Jan/2022 22:38:43] "GET /contact/index HTTP/1.1" 200 3243
[25/Jan/2022 22:38:44] "GET / HTTP/1.1" 200 4067
/opt/blogger_ui/src/app/main/settings.py changed, reloading.
Performing system checks...

January 25, 2022 - 22:38:22
Django version 3.2, using settings 'main.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
/opt/blogger_ui/src/app/main/settings.py changed, reloading.
Performing system checks...

January 25, 2022 - 22:39:53
Django version 3.2, using settings 'main.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'home' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
[25/Jan/2022 22:41:07] "GET / HTTP/1.1" 200 4067
[25/Jan/2022 22:41:09] "GET /contact/index HTTP/1.1" 200 3243
[25/Jan/2022 22:41:25] "POST /contact/index HTTP/1.1" 302 0
[25/Jan/2022 22:41:25] "GET /contact/successful HTTP/1.1" 200 2511
[25/Jan/2022 22:41:31] "GET / HTTP/1.1" 200 4067
[25/Jan/2022 22:41:50] "GET /blogger/ HTTP/1.1" 200 3630
[25/Jan/2022 22:41:53] "GET /contact/index HTTP/1.1" 200 3243
